query:
  getCohortsInterval: 60000
  startupDelay: 1000

atlas:
  url: "http://localhost:8082/WebAPI"
  cohortStatusCheckBackoffTime: 10000
  dataSource: "OHDSI-CDMV5"

omop:
  jdbcUrl: "jdbc:postgresql://localhost:5432/OHDSI"
  username: postgres
  password: postgres
  cohortResultsTable: "synpuf_results.cohort"

fhir:
  url: "http://localhost:8083/fhir"
  logEnabled: false
  systems:
    omopSubjectIdentifier: "http://ohdsi.org/omop/fhir/subject-identifier"
    omopCohortIdentifier: "http://ohdsi.org/omop/fhir/cohort-identifier"
    screeningListIdentifier: "https://fhir.miracum.org/uc1/NamingSystem/screeningListId"
    screeningListStudyReferenceExtension: "https://fhir.miracum.org/uc1/StructureDefinition/belongsToStudy"
    researchStudyAcronym: "https://fhir.miracum.org/uc1/StructureDefinition/studyAcronym"
    screeningListCoding: "https://fhir.miracum.org/uc1/CodeSystem/screeningList"

camel:
  springboot:
    name: Query
    jmx-enabled: false
    main-run-controller: true

# to configure logging levels
logging:
  level:
    org:
      springframework: "INFO"
      apache:
        camel:
          spring:
            boot: "INFO"
          impl: "INFO"
      miracum:
        recruit:
          query: "INFO"
