query:
  selector:
    matchLabels:
      - "UC1"

omop:
  jdbcUrl: "jdbc:postgresql://localhost:25432/OHDSI"
  user: postgres
  password: postgres
  cohortResultsTable: "synpuf_results.cohort"

# to configure logging levels
logging:
  level:
    org:
      springframework: "INFO"
      apache:
        camel:
          spring:
            boot: "INFO"
          impl: "DEBUG"
      miracum:
        recruit:
          query: "DEBUG"
