omop:
  jdbcUrl: "jdbc:postgresql://localhost:25432/ohdsi"
  username: "postgres"
  password: "postgres"

query:
  schedule:
    unixCron: "* * * * *" # run every minute
  webapi:
    base-url: "http://localhost:8083/WebAPI"
    auth:
      enabled: true
      login-path: "/user/login/db"
      username: "recruit-query-module"
      password: "pass123"

fhir:
  url: "http://localhost:8082/fhir"

# to configure logging levels
logging:
  level:
    org:
      springframework: "INFO"
      apache:
        camel:
          spring:
            boot: "INFO"
          impl: "DEBUG"
      miracum:
        recruit:
          query: "DEBUG"

opentracing:
  jaeger:
    enabled: true
    log-spans: true
