omop:
  jdbcUrl: "jdbc:postgresql://localhost:25432/OHDSI"
  username: "postgres"
  password: "postgres"

query:
  schedule:
    enable: true
    unixCron: "* * * * *" # run every minute

atlas:
  url: "http://localhost:8083/WebAPI"

fhir:
  # seems like there's an issue with the latest HAPI FHIR version and camel-fhir: "An attempt was made to call a method that does not exist."
  # disabling for now...
  logEnabled: false

# to configure logging levels
logging:
  level:
    org:
      springframework: "INFO"
      apache:
        camel:
          spring:
            boot: "INFO"
          impl: "DEBUG"
      miracum:
        recruit:
          query: "DEBUG"

opentracing:
  jaeger:
    log-spans: true
