version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v8.1.3
    ports:
      - "8082:8080"
    environment:
      SERVER_ADDRESS: http://localhost:8082/fhir

  omopdb:
    image: docker.miracum.org/miracum-etl/omop/empty:latest-cdm5.3.1
    ports:
      - "25432:5432"

  broadsea-webtools:
    image: docker.miracum.org/miracum-etl/omop/webtools:bf69fe02
    ports:
      - "8083:8080"
    environment:
      PGHOST: omopdb
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_PASSWORD: postgres
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh

  list:
    image: docker.miracum.org/uc1-recruit/list:2.4
    ports:
      - "8084:8080"
    environment:
      FHIR_URL: "http://fhir:8080/fhir"
      KEYCLOAK_DISABLED: "true"

  jaeger:
    image: jaegertracing/all-in-one:1.21
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
