version: "3.9"

services:
  fhir:
    image: docker.io/hapiproject/hapi:v5.6.0-distroless
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "true"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "true"
      HAPI_FHIR_FHIR_VERSION: "R4"
      HAPI_FHIR_CORS_ALLOWCREDENTIALS: "false"
      HAPI_FHIR_CORS_ALLOWED_ORIGIN: "*"
      HAPI_FHIR_NARRATIVE_ENABLED: "false"
    ports:
      - "8082:8080"

  omopdb:
    image: quay.io/miracum/omop:test-data-v3
    ports:
      - "25432:5432"

  ohdsi-webapi:
    image: docker.io/ohdsi/webapi:2.10.1
    ports:
      - "8083:8080"
    restart: on-failure
    environment:
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_PASSWORD: postgres
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi
      SECURITY_PROVIDER: "AtlasRegularSecurity"
      SECURITY_DB_DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      SECURITY_CORS_ENABLED: "true"
      SECURITY_ORIGIN: "*"
      SECURITY_DB_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      SECURITY_DB_DATASOURCE_SCHEMA: ohdsi
      SECURITY_DB_DATASOURCE_USERNAME: postgres
      SECURITY_DB_DATASOURCE_PASSWORD: postgres
      SECURITY_DB_DATASOURCE_AUTHENTICATIONQUERY: >-
        SELECT password, first_name AS firstname, middle_name AS middlename, last_name AS lastname, username
        FROM ohdsi.basic_security_users
        WHERE username = ?
    depends_on:
      - omopdb

  ohdsi-atlas:
    image: docker.io/ohdsi/atlas:2.10.1
    ports:
      - "8084:8080"
    environment:
      WEBAPI_URL: "http://localhost:8083/WebAPI/"
    volumes:
      - ./config-local.js:/usr/share/nginx/html/atlas/js/config-local.js

  list:
    image: ghcr.io/miracum/recruit/list:v2.14.2
    ports:
      - "8085:8080"
    environment:
      FHIR_URL: "http://fhir:8080/fhir"
      KEYCLOAK_DISABLED: "true"
      TRACING_ENABLED: "true"
      OTEL_EXPORTER_JAEGER_AGENT_HOST: "jaeger"

  jaeger:
    image: jaegertracing/all-in-one:1.29
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
