version: "3.7"

services:
  fhir:
    image: hapiproject/hapi:v5.4.0
    environment:
      HAPI_FHIR_VALIDATION_REQUESTS_ENABLED: "true"
      HAPI_FHIR_SUBSCRIPTION_RESTHOOK_ENABLED: "true"
      HAPI_FHIR_FHIR_VERSION: "R4"
      HAPI_FHIR_CORS_ALLOWCREDENTIALS: "false"
      HAPI_FHIR_CORS_ALLOWED_ORIGIN: "*"
    ports:
      - "8082:8080"

  omopdb:
    image: quay.io/miracum/omop:test-data
    ports:
      - "25432:5432"
    shm_size: "1g"

  broadsea-webtools:
    image: harbor.miracum.org/miracum-etl/omop/webtools:v3.0.0-rc.1-cdm5.3.1
    ports:
      - "8083:8080"
    environment:
      DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: postgres
      DATASOURCE_OHDSI_SCHEMA: ohdsi
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: ohdsi
      SPRING_BATCH_REPOSITORY_TABLEPREFIX: ohdsi.BATCH_
      FLYWAY_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
      FLYWAY_DATASOURCE_URL: jdbc:postgresql://omopdb:5432/ohdsi
      FLYWAY_DATASOURCE_USERNAME: postgres
      FLYWAY_DATASOURCE_PASSWORD: postgres
      FLYWAY_LOCATIONS: classpath:db/migration/postgresql
      FLYWAY_PLACEHOLDERS_OHDSISCHEMA: ohdsi
      FLYWAY_SCHEMAS: ohdsi
    volumes:
      - ./entrypoint.sh:/entrypoint.sh:ro
    entrypoint: /entrypoint.sh

  list:
    image: harbor.miracum.org/uc1-recruit/list:v2.8
    ports:
      - "8084:8080"
    environment:
      FHIR_URL: "http://fhir:8080/fhir"
      KEYCLOAK_DISABLED: "true"
      TRACING_ENABLED: "true"

  jaeger:
    image: jaegertracing/all-in-one:1.22
    ports:
      - 16686:16686
      - 6831:6831/udp
      - 6832:6832/udp
