version: "3.7"

services:
  fhir:
    image: docker.miracum.org/miracum-data/hapi-fhir-jpaserver:v3.0.0
    restart: always
    ports:
      - "8083:8080"
    environment:
      FHIR_VERSION: R4
      SERVER_URL: http://fhir:8080/fhir
      POSTGRES_HOST: fhir-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir
    depends_on:
      - fhir-db

  fhir-db:
    image: postgres:12.1-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fhir
    tmpfs:
      - /var/lib/postgresql/data:rw

  omopdb:
    image: docker.miracum.org/ohdsi-omop-v5/omop-db-v5:1.0.0
    ports:
      - "5432:5432"
    volumes:
      - volume-pg:/var/lib/postgresql/data

  broadsea-webtools:
    image: docker.miracum.org/ohdsi-omop-v5/broadsea-webtools:1.0.0
    ports:
      - "8082:8080"
    volumes:
      - ./config-local.js:/usr/local/tomcat/webapps/atlas/js/config-local.js:ro
    environment:
      - WEBAPI_URL=localhost:8082
      - env=webapi-postgresql
      - datasource_driverClassName=org.postgresql.Driver
      - datasource_url=jdbc:postgresql://omopdb:5432/OHDSI
      - datasource.cdm.schema=synpuf_cdm
      - datasource.ohdsi.schema=ohdsi
      - datasource_username=${DATASOURCE_USERNAME:-ohdsi_admin_user}
      - datasource_password=${DATASOURCE_PASSWORD:-admin1}
      - spring.jpa.properties.hibernate.default_schema=ohdsi
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.batch.repository.tableprefix=ohdsi.BATCH_
      - flyway_datasource_driverClassName=org.postgresql.Driver
      - flyway_datasource_url=jdbc:postgresql://omopdb:5432/OHDSI
      - flyway_schemas=ohdsi
      - flyway.placeholders.ohdsiSchema=ohdsi
      - flyway_datasource_username=${DATASOURCE_USERNAME:-ohdsi_admin_user}
      - flyway_datasource_password=${DATASOURCE_PASSWORD:-admin1}
      - flyway.locations=classpath:db/migration/postgresql

volumes:
  volume-pg:
    external: true
